from django.urls import path

from .views import (
    ChangePasswordAPIView,
    EmailVerificationAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    UserLoginAPIView,
    UserLogoutAPIView,
    UserProfileAPIView,
    UserRefreshTokenAPIView,
    UserRegistrationAPIView,
)

urlpatterns = [
    path(
        "register/",
        UserRegistrationAPIView.as_view(),
        name="user-register",
    ),
    path(
        "login/",
        UserLoginAPIView.as_view(),
        name="user-login",
    ),
    path(
        "refresh/",
        UserRefreshTokenAPIView.as_view(),
        name="token-refresh",
    ),
    path(
        "logout/",
        UserLogoutAPIView.as_view(),
        name="user-logout",
    ),
    path(
        "profile/",
        UserProfileAPIView.as_view(),
        name="user-profile",
    ),
    path(
        "change-password/",
        ChangePasswordAPIView.as_view(),
        name="change-password",
    ),
    path(
        "verified-email/",
        EmailVerificationAPIView.as_view(),
        name="verify-email",
    ),
    path(
        "password-reset/request/",
        PasswordResetRequestAPIView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/confirm/",
        PasswordResetConfirmAPIView.as_view(),
        name="password-reset-confirm",
    ),
]
